### ISSUE TITLE
Could not find PyAudio; check installation

### ISSUE THREAD

**Issue by akashjadhav3** [RohanDas28/Karen-A-Personal-Virtual-Assistant#1]
I'm in new in python but when I was run the code they show error 

F:\Git_Clone\Karen-A-Personal-Virtual-Assistant>python assistant.py
Traceback (most recent call last):
  File "C:\Users\Akash\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "assistant.py", line 59, in <module>
    query = takeCommand().lower()
  File "assistant.py", line 39, in takeCommand
    with sr.Microphone() as source:
  File "C:\Users\Akash\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Users\Akash\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by RohanDas28** [comment]
Try Pip Install pyaudio or if that does not works try the following:
Download suitable version of PyAudio File: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio

Then Open CMD type : C:\Users\Programs\Python\Python37\Scripts add "pip install" file location where you downloaded the PyAudio whl file.
example:C:\Users\Programs\Python\Python37\Scripts>pip install C:\Users\Desktop\Projects\PyAudio-0.2.11-cp37-cp37m-win_amd64.whl

**Comment by MadhavSharma08** [comment]
Bro my assistant keeps listening and does not return output (maine harry bhai ka code copy kiya hai)and i have already installed pyaudio , so no issue with that also . It just wishes me and then it keeps on listening . PLZ HELP !!🙏🙏🙏
